### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by khaledsobhy83** [Geotab/sdk#36]
Hello,

It is not really an issue but more of a help, I am trying to generate a report on top of your APIs that shows the duration and distance for drivers per duty status (D and ON ), in other words how many hours, miles the driver was driving and On Duty. I am using The DutyStatusLogs but I am seeing only log date. It does not tell me for how long the status was D and same for ON. Can you help me with that?

Regards,
Khaled

**Comment by beefo** [comment]
https://helpdesk.geotab.com/hc/en-us/community/posts/360047841152-How-to-get-Get-D-and-ON-duration-and-miles-for-drivers-using-DutyStatusLog-
